Create some UI components + fixed code
etimesoy/Find-and-Learn pull request #25
Opened 2022-03-26 15:26 UTC by Sixezr

Создал PasswordTextField + пофиксил код с инитом, который вызывался дважды

2022-03-27 20:49 UTC, etimesoy requested changes
И еще поправишь опечатку? Там еще в PasswordTextField надо будет поменять название проперти.
<img width="275" alt="Screenshot" src="https://user-images.githubusercontent.com/86663214/160300394-6ffbd10b-b1ce-4ecf-94db-bb5412d22b36.png">

2022-03-27 20:49 UTC, etimesoy commented on Source/Components/TextFields/PasswordTextField.swift
> +        button.addTarget(self, action: #selector(showHidePassword(_:)), for: .touchUpInside)
Как насчет того, чтобы вынести эту кнопку в lazy private var проперти?

2022-03-28 10:43 UTC, Sixezr commented on Source/Components/TextFields/PasswordTextField.swift
> +        button.addTarget(self, action: #selector(showHidePassword(_:)), for: .touchUpInside)
она не переиспользуется, зачем?

2022-03-29 09:43 UTC, etimesoy approved these changes

2022-03-29 09:51 UTC, merged