Authorization module done
etimesoy/Find-and-Learn pull request #31
Opened 2022-04-01 20:27 UTC by Sixezr

2022-04-03 19:50 UTC, etimesoy requested changes

2022-04-03 19:50 UTC, etimesoy commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationAssembly.swift
> +    func assemble() -> UIViewController {
По аналогии с `PasswordRecoveryViewController` можно сделать статик

2022-04-03 19:50 UTC, etimesoy commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationPresenter.swift
> +    // MARK: - Dependencies
`// MARK: Dependencies`

2022-04-03 19:50 UTC, etimesoy commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationViewController.swift
> +        button.titleLabel?.font = button.titleLabel?.font.withSize(14)
Можно вынести в константы число 14.
Можно у `UIButton` создать `extension`, например, `setFontSize(_:)`, чтобы упростить `button.titleLabel?.font = button.titleLabel?.font.withSize(14)`.

2022-04-03 19:50 UTC, etimesoy commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationViewController.swift
> +        let button = UIButton()
Не получится здесь тоже CommonButton использовать?

2022-04-03 19:50 UTC, etimesoy commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationViewController.swift
> +    private var presenter: AuthorizationViewOutput
Можно `let`

2022-04-03 19:50 UTC, etimesoy commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationViewController.swift
> +    // MARK: Init
`// MARK: Init & deinit`

2022-04-03 19:50 UTC, etimesoy commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationViewController.swift
> +    @objc private func keyboardWillShow(notification: Notification) {
Здесь лучше сделать по аналогии с PasswordRecoveryViewController: если клавиатура загорожает кнопку "войти", то добавить расстояние между нижней кнопкой и этой клавиатурой + оба текст филда поднять немного повыше

2022-04-03 19:50 UTC, etimesoy commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationViewController.swift
> +            textField.resignFirstResponder()
В будущем наверное было бы неплохо сделать так, чтобы нажатие на "Ввод" на клавиатуре вызывало тот же метод, что и нажатие на кнопку "Войти"

2022-04-04 06:27 UTC, Sixezr commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationViewController.swift
> +    @objc private func keyboardWillShow(notification: Notification) {
мб на потом оставить? когда будет свободное время

2022-04-04 19:09 UTC, etimesoy approved these changes
Хорошо, расстояние между UI элементами можно попозже поправить

2022-04-04 19:10 UTC, merged