Add History words module
etimesoy/Find-and-Learn pull request #37
Opened 2022-04-05 10:30 UTC by etimesoy

2022-04-05 19:24 UTC, Sixezr requested changes
у себя пока не запускал, завтра запущу

2022-04-05 19:24 UTC, Sixezr commented on Source/Scenarios/Main/Dictionary/Modules/History Words/Presenter/HistoryWordsPresenter.swift
> +            self?.view?.showWords(words)
обернуть в DispatchQueue.main.async

2022-04-05 19:24 UTC, Sixezr commented on Source/Scenarios/Main/Dictionary/Modules/History Words/View/HistoryWordsTableViewCell.swift
> +        labelsStackView.addArrangedSubview(searchesCountLabel)
layoutSubviews может вызываться не один раз, тогда код будет добавлять элементы много раз

2022-04-05 19:24 UTC, Sixezr commented on Source/Scenarios/Main/Dictionary/Modules/History Words/View/HistoryWordsTableViewCell.swift
> +        translationsLabel.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
а зачем вообще тут расставлять констреинты? почему не в ините, например?

2022-04-05 19:24 UTC, Sixezr commented on Source/Scenarios/Main/Dictionary/Modules/History Words/View/HistoryWordsTableViewCell.swift
> +    }
как по мне лишнее, просто ставишь новый текст и все

2022-04-05 19:24 UTC, Sixezr commented on Source/Scenarios/Main/Dictionary/Modules/History Words/View/HistoryWordsTableViewCell.swift
> +    }
вот в методе в configure ставишь текст и все

2022-04-05 19:24 UTC, Sixezr commented on Source/Scenarios/Main/Dictionary/Modules/History Words/View/HistoryWordsViewController.swift
> +    private let output: HistoryWordsViewOutput
мб presenter?

2022-04-05 19:24 UTC, Sixezr commented on Source/Scenarios/Main/Dictionary/Modules/History Words/View/HistoryWordsViewController.swift
> +        output.viewDidLoad()
обернуть в DispatchQueue.global(qos: .utility).async

2022-04-05 19:29 UTC, etimesoy commented on Source/Extensions/DateFormatter+Extensions.swift
> +    static let EEEEMMMd: DateFormatter = {
что насчет `weekDayMonthDayFormatter`?

2022-04-06 07:26 UTC, Sixezr commented
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/71031730/161918968-66fa2ad9-cebe-484c-a168-193633a610f6.png">
не запускается, pod install & update писал, там видимо проблемы в xcodeproj файле

2022-04-06 07:26 UTC, Sixezr commented
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/71031730/161919114-e3a38d6a-1286-4edc-bd77-8729c31e28bd.png">
вот

2022-04-06 07:28 UTC, Sixezr commented
> <img alt="image" width="1552" src="https://user-images.githubusercontent.com/71031730/161919114-e3a38d6a-1286-4edc-bd77-8729c31e28bd.png">
> 
> вот

проблемы только на ipod 15.2, на 13 iOS норм

2022-04-06 07:29 UTC, Sixezr commented
> > <img alt="image" width="1552" src="https://user-images.githubusercontent.com/71031730/161919114-e3a38d6a-1286-4edc-bd77-8729c31e28bd.png">
> > вот
> 
> проблемы только на ipod 15.2, на 13 iOS норм

+ на SE 2 не запускается iOS 15.2

2022-04-06 15:56 UTC, Sixezr approved these changes

2022-04-06 15:56 UTC, Sixezr commented on Source/Scenarios/Main/Dictionary/Modules/History Words/View/HistoryWordsTableViewCell.swift
> +class HistoryWordsTableViewCell: UITableViewCell {
final, проглядел как-то в прошлый раз

2022-04-06 16:00 UTC, merged