Studying module done
etimesoy/Find-and-Learn pull request #49
Opened 2022-04-23 20:44 UTC by Sixezr

2022-04-24 16:53 UTC, etimesoy requested changes
Есть ощущение, что для FinishStudyingView и FlashCardView можно было создать единый суперкласс, куда можно было бы вынести повторяющуюся работу с backgroundColor и layer (см. метод configure), но не критично.

2022-04-24 16:53 UTC, etimesoy commented on Source/Scenarios/Main/Decks/Modules/Studying/StudyingAssembly.swift
> +        ]
собрал все классы 🤌

2022-04-24 16:53 UTC, etimesoy commented on Source/Scenarios/Main/Decks/Modules/Studying/View/StudyingViewController.swift
> +                        action: #selector(self.panCard(_:)))
А если сразу при инициализации на все вьюшки карточек навесить UIPanGestureRecognizer, не прокатит?

2022-04-25 11:43 UTC, Sixezr commented on Source/Scenarios/Main/Decks/Modules/Studying/View/StudyingViewController.swift
> +                        action: #selector(self.panCard(_:)))
там могут возникнуть кейсы, когда карточку сзади смогут смахнуть, а это не нужно

2022-04-25 11:44 UTC, Sixezr commented on Source/Components/Views/FlashCardView.swift
> +        learnedMessageView.isHidden = true
да, в целом можно, но я так думаю оставить

2022-04-25 13:41 UTC, merged