Add working with Core Data and UserDefaults
etimesoy/Find-and-Learn pull request #65
Opened 2022-05-11 13:51 UTC by etimesoy

2022-05-14 10:35 UTC, Sixezr requested changes

2022-05-14 10:35 UTC, Sixezr commented on Source/Entities/DeckEntity.swift
> +public final class DeckEntity: NSManagedObject {
зачем ```public```?

2022-05-14 10:35 UTC, Sixezr commented on Source/Entities/DeckEntity.swift
> +    public init(
и тут зачем ```public```?

2022-05-14 10:35 UTC, Sixezr commented on Source/Entities/DeckEntity.swift
> +    }
```@available(*, unavailable)``` не нужно, раз там fatal error

2022-05-14 10:35 UTC, Sixezr commented on Source/Entities/ExampleEntity.swift
> +        let entity = NSEntityDescription.entity(forEntityName: "ExampleEntity", in: context)!
правильно понимаю, что тут никогда краша не будет? то есть зависит от написания имени сущности?

2022-05-14 10:35 UTC, Sixezr commented on Source/Entities/WordEntity.swift
> +// MARK: Generated accessors for translations
по стилю лучше ```// MARK: - Some.... \n\n```

2022-05-14 10:35 UTC, Sixezr commented on Source/Entities/WordEntity.swift
> +// MARK: Generated accessors for translations
марк с -, потому что не иннер

2022-05-14 10:35 UTC, Sixezr commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationAssembly.swift
> +            dataManager: DataManager.shared
синглтон?

2022-05-14 10:35 UTC, Sixezr commented on Source/Services/Achievements Manager/AchievementsManager.swift
> +    }
можно сделать модельку, которая будет ```Codable```, сохранять массив этих моделек и кастить в Achievement

2022-05-14 10:35 UTC, Sixezr commented on Source/Services/Achievements Manager/AchievementsManager.swift
> +    }
там вроде джоснку нужно сохранять, а не саму модельку, видел гайды много раз

2022-05-14 10:35 UTC, Sixezr commented on Source/Services/Data Manager/DataManager.swift
> +    }
токен все таки лучше в кейЧейн

2022-05-14 10:35 UTC, Sixezr commented on Source/Services/User Manager/UserManager.swift
> +    func getUser(completion: @escaping (User) -> Void)
давай лучше тогда без комплишна возвращать, раз у нас userDefaults

2022-05-14 10:35 UTC, Sixezr commented on Source/Services/User Manager/UserManager.swift
> +        let accountIsActiveKey = userDefaults.bool(forKey: accountIsActiveKey)
тут тоже лучше создать модель Encodable и сохранять ее

2022-05-14 10:35 UTC, Sixezr commented on Source/Services/User Manager/UserManager.swift
> +        let accountIsActiveKey = userDefaults.bool(forKey: accountIsActiveKey)
можно энкодить enum по rawValue

2022-05-14 14:29 UTC, etimesoy commented on Source/Entities/DeckEntity.swift
> +public final class DeckEntity: NSManagedObject {
Насколько помню по умолчанию так сгенерировалось, да и к тому же все методы и проперти тоже.

2022-05-14 14:30 UTC, etimesoy commented on Source/Entities/DeckEntity.swift
> +    public init(
Ну раз все остальное `public`, то и здесь тоже так поставил

2022-05-14 14:31 UTC, etimesoy commented on Source/Entities/DeckEntity.swift
> +    }
Если я правильно понял, то это нужно для подсказок в xcode, т.е. чтобы он подсказывал только те конструкторы, у которых норм реализация

2022-05-14 14:35 UTC, etimesoy commented on Source/Entities/ExampleEntity.swift
> +        let entity = NSEntityDescription.entity(forEntityName: "ExampleEntity", in: context)!
Да, все так

2022-05-14 14:40 UTC, etimesoy commented on Source/Scenarios/Entrance/Modules/Authorization/AuthorizationAssembly.swift
> +            dataManager: DataManager.shared
Можем поменять, я просто еще не до конца разобрался будет ли норм работать без него. В противном случае же получится так, что создается контекст для каждого экземпляра класса DataManager, и вроде бы их потом еще мержить надо, но я еще уточню это.

2022-05-14 15:09 UTC, etimesoy commented on Source/Services/User Manager/UserManager.swift
> +    func getUser(completion: @escaping (User) -> Void)
Можно все равно обернуть в `DispatchQueue.global().async`, чтобы не нагружать `main` очередь

2022-05-14 15:31 UTC, Sixezr commented on Source/Entities/DeckEntity.swift
> +public final class DeckEntity: NSManagedObject {
не нужно в целом, если бы у нас многомодульность была, то да

2022-05-14 15:31 UTC, Sixezr commented on Source/Entities/DeckEntity.swift
> +    }
лишнее))

2022-05-14 15:32 UTC, Sixezr commented on Source/Services/User Manager/UserManager.swift
> +    func getUser(completion: @escaping (User) -> Void)
userDefaults не нагружает ее почти

2022-05-14 15:33 UTC, etimesoy commented on Source/Services/User Manager/UserManager.swift
> +    func getUser(completion: @escaping (User) -> Void)
Окей

2022-05-14 16:31 UTC, etimesoy commented on Source/Services/Achievements Manager/AchievementsManager.swift
> +    }
Поменял словарь на массив, думаю попроще логика стала, чекни

2022-05-14 16:39 UTC, Sixezr commented on Source/Services/Achievements Manager/AchievementsManager.swift
> +            userDefaults.set(emptyAchievementsArray, forKey: achievementsArrayKey)
зачем сохранять пустой массив?

2022-05-14 16:57 UTC, etimesoy commented on Source/Services/Achievements Manager/AchievementsManager.swift
> +            userDefaults.set(emptyAchievementsArray, forKey: achievementsArrayKey)
Чтобы потом в методе `checkNewAchievements` можно было его легко получить и обновить

2022-05-15 08:48 UTC, Sixezr commented on Source/Services/Data Manager/DataManager.swift
> +        _ = KeyChainManager.save(key: backendTokenKeyChainKey, data: Data(from: token))
почему не Void, если все равно игнорируем статус?

2022-05-15 09:10 UTC, etimesoy commented on Source/Services/Data Manager/DataManager.swift
> +        _ = KeyChainManager.save(key: backendTokenKeyChainKey, data: Data(from: token))
В методе `save` у `KeyChainManager` последняя операция это `SecItemAdd`, и это она возвращает статус. Поэтому, если сделаем этот метод Void, то придется внутри него аналогично игнорировать. В целом, я думаю можно оставить так, вдруг понадобится еще. Вдруг наткнемся на такие случаи, когда надо будет это обрабатывать.

2022-05-15 17:18 UTC, Sixezr approved these changes
маленькое замечание по модельки User и State, поправишь и мерджи

2022-05-15 17:18 UTC, Sixezr commented on Source/Models/User.swift
> +struct User: Codable {
не, эти модельки точно не должны быть ```Codable```, нужно сделать другую сущность и ее сохранять

2022-05-15 17:18 UTC, Sixezr commented on Source/Models/User.swift
> +enum AccountState: Codable {
аналогично с ```User```

2022-05-16 10:40 UTC, merged